In [1]:
import torch
import torch.nn as nn

In [2]:
# 如果 前一个是物品的个数 后面是物品embedding 维度
# 有趣的事情发生了
# 在文章中 咱只需要 确认一个用户编码 还有一个物品编码就好了嘛
embedding = nn.Embedding(10, 3)

In [3]:
input = torch.LongTensor([1,2,3,4,5,6,7,8,9])

In [19]:
input_embed = embedding(input)

In [20]:
input_embed

tensor([[ 0.3974, -0.0988,  0.3758],
        [-0.0685, -0.5384, -0.4036],
        [-0.1967,  1.4902, -1.7089],
        [ 1.6544, -0.3214,  0.1649],
        [ 0.6180,  0.9051,  0.7922],
        [ 0.0805,  0.9490, -0.6889],
        [ 1.4841,  0.8647,  0.0356],
        [ 0.2589,  1.4257, -0.8124],
        [ 0.6450,  0.5506,  0.4622]], grad_fn=<EmbeddingBackward0>)

In [21]:
input_embed[1]

tensor([-0.0685, -0.5384, -0.4036], grad_fn=<SelectBackward0>)

In [4]:
input_embed = embedding(torch.LongTensor([1,2,3,8]))
input_embed

tensor([[ 0.6689, -0.1024,  0.9258],
        [-0.2602,  0.0980,  1.3343],
        [ 0.1694,  0.2633,  1.5107],
        [ 0.4026,  0.3061,  1.0020]], grad_fn=<EmbeddingBackward0>)

In [5]:
print(input_embed.size())

torch.Size([4, 3])
